name: vivalabuilda

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  complete-demo-sync-check:
    runs-on: ubuntu-latest
    env:
      COMPLETE_DEMO_ARGS: --rm -v ${{ github.workspace }}:/workdir
      COMPLETE_DEMO_DIR: 'deploy/kubernetes/'
      COMPLETE_DEMO_IMAGE: 'manifests-image'
    steps:
      - uses: actions/checkout@v2

      # Build image
      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t ${{secrets.DOCKER_IMAGE_NAME}} ${{secrets.$DOCKER_IMAGE_DIR}}

      # Authenticate with GCP
      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GD_GCP_GRIDU_DEVOPS_T1_T2 }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential helper
      - name: Configure Docker
        run: gcloud auth configure-docker

      # Tag and push the image to Google Container Registry
      - name: Push image to GCR
        run: |
          docker tag ${{secrets.DOCKER_IMAGE_NAME}} gcr.io/${{secrets.GCP_PROJECT}}/${{secrets.DOCKER_IMAGE_NAME}}
          docker push gcr.io/${{secrets.GCP_PROJECT}}/${{secrets.DOCKER_IMAGE_NAME}}