name: GKE Cluster Creation

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

#      - name: Authenticate with GCP
#        run: |
#          cd Terraform
#          echo "$GCP_SA_KEY" > gcp-key.json
#          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
#        env:
#          GCP_SA_KEY: ${{ secrets.GD_GCP_GRIDU_DEVOPS_T1_T2 }}

      - name: Initialize Terraform
        run: |
          cd Terraform
          echo "$GCP_SA_KEY" > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json 
          terraform -chdir=${{ secrets.TF_DIR }} init --reconfigure
        env:
          GCP_SA_KEY: ${{ secrets.GD_GCP_GRIDU_DEVOPS_T1_T2 }}

      - name: Format Terraform Code
        run: terraform -chdir=${{ secrets.TF_DIR }} fmt

      - name: Terraform Plan
        run: terraform -chdir=${{ secrets.TF_DIR }} plan'

      - name: Apply Terraform
        run: terraform -chdir=${{ secrets.TF_DIR }} apply -auto-approve
